- name: Transfer the script
  copy: src=./create_policy.sh dest=/etc/swift/ mode=0755

- name: Execute the script
  command: /etc/swift/create_policy.sh {{policy_id}} {{name}} {{partitions}} {{replicas}} {{time}} {{storage_node}}

- name: Obtain swift.conf to distribute to storage nodes (from serverA to serverB)
  fetch: src=/etc/swift/swift.conf dest=/tmp/swift.conf flat=yes

- name: Obtain ring file to distribute to storage nodes (from serverA to serverB)
  fetch: src=/etc/swift/object-{{policy_id}}.ring.gz dest=/tmp/object-{{policy_id}}.ring.gz flat=yes
